---
title: "Final Project Data Preparation"
author: "Md Jalal Uddin"
date: "May 14, 2019"
output: html_document
---

```{r}

library(plyr)
library(dplyr)
library(ggmap)
library(ggplot2)
library(shiny)

```


```{r}

#register_google(key = "AIzaSyBBqaWHjaehbPKb0-3QSf2ShaIaCNzxnRk")

#has_goog_key()

```

```{r}

#Load data
GVdata1 <- read.csv(url('https://raw.githubusercontent.com/uddinjalal1983/DATA_608/master/DATA_608_Final_Project/Final_Project_Data/Data_all.csv'))

head(GVdata1, n=5)

```


```{r}

GVdata1$FullAddress <- paste0(GVdata1$Address, ", ", GVdata1$City.Or.County, ", ", GVdata1$State)
geo_reply <- geocode(GVdata1$FullAddress, override_limit=TRUE)
GVdata1 <- cbind(GVdata1, geo_reply)

head(GVdata1,n=20)

GVdata1 <- select(GVdata1, Incident.Date, FullAddress, lat, lon, X..Killed, X..Injured)
names(GVdata1) <- c("Date", "Address", "lat", "lon", "Killed", "Injured")

GVdata1$Date <- as.Date(GVdata1$Date, format="%B %d, %Y")
GVdata1 <- GVdata1[order(GVdata1$Date), ]

GVdata1$Content <- paste0("<b>Date: </b>", GVdata1$Date, "<br/>",
                      "<b>Killed: </b>", GVdata1$Killed, "<br/>",
                      "<b>Injured: </b>", GVdata1$Injured, "<br/>",
                      "<b>Location: </b>", GVdata1$Address)

head(GVdata1,n=20)

```

```{r}
#save th GVdata1 file into my local computer as .csv file
write.csv(GVdata1, file = "C:/Users/sql_ent_svc/Desktop/Data_608/FinalData.csv", row.names = F)


```

```{r}

#saving the GVdata1.csv file as .rds file

#Load data
Rdsdata <- read.csv(url('https://raw.githubusercontent.com/uddinjalal1983/DATA_608/master/DATA_608_Final_Project/Final_Project_Data/GVFinalData.csv'))

head(Rdsdata, n=5)

saveRDS(Rdsdata, file = "C:/Users/sql_ent_svc/Desktop/Data_608/GVFinalData.rds")


```


